Added support for comments on other sites than SO, added placeholders
SOBotics/AdvancedFlagging pull request #281
Opened 2024-01-17 02:27 UTC by fastnlight0

Added support for comments and Answer related NAA options for sites other than Stack Overflow.

In addition, similar to AutoReviewComments, I added 3 placeholders:
|Placeholder|Description|Example|
|------------|-----------|---------|
|%SITENAME%|The site name|Stack Overflow, Super User|
|%SITEURL%|The domain of the current site|stackoverflow.com, money.stackexchange.com|
|%OP%|The author of the question/answer|fastnlight|

2024-01-24 18:04 UTC, double-beep requested changes
Thanks for the PR! I will test the changes in the weekend.

2024-01-24 18:04 UTC, double-beep commented on src/popover.ts
> +        comment = comment.replace(/%OP%/, opName);
This will only replace the first occurrence of each placeholder.

2024-01-25 13:15 UTC, double-beep commented
Hmm... I'm reluctant to approve this. IIRC, the reason that adding answer-related comments via the AF menu on non-SO sites was disabled is because of [this Charcoal policy](https://charcoal-se.org/training/reports.html#comments-on-reported-posts):

> You should not leave comments under a post reported by SmokeDetector, unless you are otherwise familiar with that Stack Exchange site. In general, that means you participate on the site for more than responding to SmokeDetector reports and/or viewing a few Hot Network Questions.

2024-06-03 10:34 UTC, double-beep commented
I'm sorry for the delay in responding. Since I've rewritten some parts of the code this PR modifies, could you open a new PR with your changes? Thanks!

2024-06-03 10:34 UTC, closed without merging

2024-06-03 14:24 UTC, fastnlight0 commented
@double-beep Done! #292